### ISSUE TITLE
I'm able to open the website, please fix this : )

### ISSUE THREAD

**Issue by adurhmn** [VishwaGauravIn/impossible-to-open-webpage#2]
<img width="1512" alt="Screenshot 2024-05-22 at 4 40 31 PM" src="https://github.com/VishwaGauravIn/impossible-to-open-webpage/assets/67814826/c19469a1-618b-4f79-b421-9bc42323626e">

**Comment by VishwaGauravIn** [comment]
This website will work only when opened in the new tab on click [target = _blank] but if you try to copy the link and paste it into the browser, you will see just a blank page.
I shared this info on my [LinkedIn post](https://www.linkedin.com/posts/vishwagauravin_its-not-possible-to-open-this-website-activity-7196156880086331392-TILm?utm_source=share&utm_medium=member_desktop), forgot to mention in the repository.
